name: MAIN Workflow

on:
  push:
    branches:
      - main

jobs:
  docker-build-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build API Docker image
        run: docker build -t ghcr.io/lyttledevelopment/kleine-stapjes-grote-droom:main .

      - name: Push API Docker image to GitHub Container Registry
        run: docker push ghcr.io/lyttledevelopment/kleine-stapjes-grote-droom:main
